version: '3.8'

services:
  # Development application with hot reload
  web:
    build:
      context: .
      target: development
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=True
      - DATABASE_URL=sqlite:///helpdesk_dev.db
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.pytest_cache
    depends_on:
      - redis
    networks:
      - helpdesk-dev-network
    command: ["python", "app.py"]

  # Redis for development
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - helpdesk-dev-network
    
  # MySQL for testing database integration
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dev_root_password
      - MYSQL_DATABASE=helpdesk_dev
      - MYSQL_USER=dev_user
      - MYSQL_PASSWORD=dev_password
    volumes:
      - mysql_dev_data:/var/lib/mysql
    networks:
      - helpdesk-dev-network
    profiles:
      - mysql

  # MongoDB for development
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dev_mongo
      - MONGO_INITDB_ROOT_PASSWORD=dev_mongo_password
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - helpdesk-dev-network
    profiles:
      - mongodb

volumes:
  mysql_dev_data:
  mongodb_dev_data:

networks:
  helpdesk-dev-network:
    driver: bridge