# Generated by Django 5.0.6 on 2025-10-22 11:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgearticle',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Rich text editor für formatierte Inhalte', verbose_name='content'),
        ),
    ]
